// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package html2pdfsocket

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4b360f88DecodeGithubComIharivHtml2pdfsocket(in *jlexer.Lexer, out *ForPdf) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Url":
			out.Url = string(in.String())
		case "Html":
			out.Html = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4b360f88EncodeGithubComIharivHtml2pdfsocket(out *jwriter.Writer, in ForPdf) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Url\":")
	out.String(string(in.Url))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Html\":")
	out.String(string(in.Html))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ForPdf) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4b360f88EncodeGithubComIharivHtml2pdfsocket(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ForPdf) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4b360f88EncodeGithubComIharivHtml2pdfsocket(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ForPdf) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4b360f88DecodeGithubComIharivHtml2pdfsocket(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ForPdf) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4b360f88DecodeGithubComIharivHtml2pdfsocket(l, v)
}
func easyjson4b360f88DecodeGithubComIharivHtml2pdfsocket1(in *jlexer.Lexer, out *Connect) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Address":
			out.Address = string(in.String())
		case "Port":
			out.Port = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4b360f88EncodeGithubComIharivHtml2pdfsocket1(out *jwriter.Writer, in Connect) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Address\":")
	out.String(string(in.Address))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Port\":")
	out.String(string(in.Port))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Connect) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4b360f88EncodeGithubComIharivHtml2pdfsocket1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Connect) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4b360f88EncodeGithubComIharivHtml2pdfsocket1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Connect) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4b360f88DecodeGithubComIharivHtml2pdfsocket1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Connect) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4b360f88DecodeGithubComIharivHtml2pdfsocket1(l, v)
}
